// Generated by CoffeeScript 1.4.0
(function() {

  exports.createSession = function(shopname, permanent_token) {
    return new (require(__dirname + "/session"))(shopname, permanent_token);
  };

}).call(this);
