// Generated by CoffeeScript 1.4.0
(function() {
  var Blog, Order, Product, Resource, Session;

  Blog = require('./resources/blog');

  Product = require('./resources/product');

  Order = require('./resources/order');

  Resource = require('./resource');

  Session = (function() {

    function Session(store_name, persistent_token) {
      this.store_name = store_name;
      this.persistent_token = persistent_token;
      this.protocol = 'https';
      this.registerOAuthToken();
      this.blog = new Blog(this.site());
      this.product = new Product(this.site());
      this.order = new Order(this.site());
    }

    Session.prototype.onRedirectUrl = function(url, cb) {
      var _this = this;
      return url.replace(/\?code=[\w\d]+/, function(code) {
        var temp_token;
        temp_token = code.split('=')[1];
        return _this.requestPermanentAccessToken(temp_token, function(persistent_token) {
          _this.persistent_token = persistent_token;
          _this.registerOAuthToken();
          return process.nextTick(function() {
            return cb();
          });
        });
      });
    };

    Session.prototype.requestPermanentAccessToken = function(temp_token, cb) {
      var params,
        _this = this;
      params = "client_id=" + this.api_key + "&client_secret=" + this.secret + "&code=" + temp_token;
      return Resource.post("" + (this.site()) + "/oauth/access_token", 'oauth', params, function(err, response) {
        if (err != null) {
          throw err;
          return;
        }
        response = JSON.parse(response);
        return process.nextTick(function() {
          return cb(response.access_token);
        });
      });
    };

    Session.prototype.site = function() {
      return "" + this.protocol + "://" + this.store_name + ".myshopify.com/admin";
    };

    Session.prototype.registerOAuthToken = function() {
      if (this.persistent_token !== null) {
        return Resource.setOAuthToken(this.persistent_token);
      }
    };

    return Session;

  })();

  module.exports = Session;

}).call(this);
